name: epic-review
description: "Human-in-the-loop PR review, merge, and rebase cycle for post-execute-epic stacked PR chains"
author: "BMad"

config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/epic-review"
instructions: "{installed_path}/workflow.md"

variables:
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"
  epics_file: "{planning_artifacts}/epics.md"
  state_file: "{implementation_artifacts}/epic-review-state.yaml"
  execute_epic_state_file: "{output_folder}/epic-execution-state.yaml"
