{{- if .Values.auth.bootstrapApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fila.fullname" . }}-auth
  labels:
    {{- include "fila.labels" . | nindent 4 }}
type: Opaque
data:
  bootstrap-apikey: {{ .Values.auth.bootstrapApiKey | b64enc }}
{{- end }}
