apiVersion: v1
kind: Service
metadata:
  name: {{ include "fila.fullname" . }}
  labels:
    {{- include "fila.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.cluster.enabled }}
    - port: {{ .Values.cluster.port }}
      targetPort: cluster
      protocol: TCP
      name: cluster
    {{- end }}
  selector:
    {{- include "fila.selectorLabels" . | nindent 4 }}
---
{{- if .Values.cluster.enabled }}
# Headless service for StatefulSet DNS discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fila.fullname" . }}-headless
  labels:
    {{- include "fila.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.cluster.port }}
      targetPort: cluster
      name: cluster
  selector:
    {{- include "fila.selectorLabels" . | nindent 4 }}
{{- end }}
